language: node_js
node_js:
  - "10.13"
before_script:
  - cd ui
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
deploy:
  provider: page
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: dist
