matrix:
  include:
    - language: rust
      rust:
        - nightly
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true

    - language: node.js
      node_js: "12.0"
      before_script:
        - cd ui
      script:
        - npm install
        - ng build --prod --base-href https://aselsiriwardena.github.io/rust-rocket-angular-seed/
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: ./ui/dist/ui/
        on:
          all_branches: true

notifications:
  email: aselindula@gmail.com